### ISSUE TITLE
맹한모코코 출현!

### ISSUE THREAD

**Issue by TProgramer** [SSAFY-Seoul-Algorithm-Study/Git-Practice#12]
![맹한모코코](https://user-images.githubusercontent.com/77713508/230837298-8737e91c-ab3c-4f67-89c3-ccc19ce2c741.jpg)

야생의 `맹한모코코`가 나타났다!

**Comment by mongsuokki** [comment]
또 늦었어!!!

**Comment by chaeyeong222** [comment]
우하하 새로고침 오백번 함

**Comment by chickennight** [comment]
느림보 최주호

**Comment by chickennight** [comment]
끝~
