### ISSUE TITLE
인사모코코 출현!

### ISSUE THREAD

**Issue by TProgramer** [SSAFY-Seoul-Algorithm-Study/Git-Practice#17]
![인사모코코](https://user-images.githubusercontent.com/77713508/230843346-b9d92aa1-14a3-4d78-a20d-c9b4a0b7847b.jpg)

야생의 `인사모코코`가 나타났다!

**Comment by chickennight** [comment]
모코코 중복 포획가능한가요?

**Comment by TProgramer** [comment]
> 모코코 중복 포획가능한가요?

퇴소처리 시켜드립니다

**Comment by chickennight** [comment]
쳇

**Comment by TProgramer** [comment]
PR 취소했으니 다시 시도하세요~
