### ISSUE TITLE
꺼억모코코 출현!

### ISSUE THREAD

**Issue by TProgramer** [SSAFY-Seoul-Algorithm-Study/Git-Practice#9]
![image](https://user-images.githubusercontent.com/77713508/230809262-bf6abb0c-a2f9-400d-abb9-953aedde9279.png)

야생의 `꺼억모코코`가 나타났다!

**Comment by mongsuokki** [comment]
이거 내가 집가서 해도됨?

**Comment by TProgramer** [comment]
> 이거 내가 집가서 해도됨?

여기서도 5분이면 할 수 있어

**Comment by mongsuokki** [comment]
지금 해보는중

**Comment by TProgramer** [comment]
굳굳
